import { Injectable } from '@angular/core';

import * as XLSX from 'xlsx';

import { saveAs } from 'file-saver';

import jsPDF from 'jspdf';

import autoTable from 'jspdf-autotable';

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  constructor() {}

  private getHeader() {

    return {

      companyName:
        localStorage.getItem('companyName') ||
        'My Company',

      generatedBy:
        localStorage.getItem('userName') ||
        'Administrator',

      generatedDate:
        new Date().toLocaleDateString(),

      generatedTime:
        new Date().toLocaleTimeString()

    };

  }

  // =====================================
  // CSV EXPORT
  // =====================================

  exportCsv(
    data: any[],
    title: string
  ): void {

    if (!data.length) {
      return;
    }

    const header =
      this.getHeader();

    let csv =

`${header.companyName}
${title} Report

Generated Date,${header.generatedDate}
Generated Time,${header.generatedTime}
Generated By,${header.generatedBy}

`;

    const columns =
      Object.keys(data[0]);

    csv += columns.join(',');

    csv += '\n';

    data.forEach(row => {

      csv += columns
        .map(col => row[col])
        .join(',');

      csv += '\n';

    });

    const blob =
      new Blob(
        [csv],
        {
          type:
            'text/csv;charset=utf-8;'
        }
      );

    saveAs(
      blob,
      `${title}.csv`
    );

  }

  // =====================================
  // EXCEL EXPORT
  // =====================================

  exportExcel(
    data: any[],
    title: string
  ): void {

    if (!data.length) {
      return;
    }

    const header =
      this.getHeader();

    const worksheet =
      XLSX.utils.json_to_sheet([]);

    XLSX.utils.sheet_add_aoa(
      worksheet,
      [
        [header.companyName],
        [`${title} Report`],
        [],
        ['Generated Date', header.generatedDate],
        ['Generated Time', header.generatedTime],
        ['Generated By', header.generatedBy],
        []
      ],
      {
        origin: 'A1'
      }
    );

    XLSX.utils.sheet_add_json(
      worksheet,
      data,
      {
        origin: 'A8',
        skipHeader: false
      }
    );

    const workbook =
      XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      title
    );

    XLSX.writeFile(
      workbook,
      `${title}.xlsx`
    );

  }

  // =====================================
  // PDF EXPORT
  // =====================================

  exportPdf(
    data: any[],
    title: string
  ): void {

    if (!data.length) {
      return;
    }

    const header =
      this.getHeader();

    const doc =
      new jsPDF();

    doc.setFontSize(16);

    doc.text(
      header.companyName,
      14,
      15
    );

    doc.setFontSize(12);

    doc.text(
      `${title} Report`,
      14,
      25
    );

    doc.text(
      `Generated Date : ${header.generatedDate}`,
      14,
      35
    );

    doc.text(
      `Generated Time : ${header.generatedTime}`,
      14,
      42
    );

    doc.text(
      `Generated By : ${header.generatedBy}`,
      14,
      49
    );

    const columns =
      Object.keys(data[0]);

    const rows =
      data.map(
        row =>
          columns.map(
            col =>
              row[col]
          )
      );

    autoTable(doc, {

      head: [columns],

      body: rows,

      startY: 60

    });

    doc.save(
      `${title}.pdf`
    );

  }

}